version: "3.5"

services:
  web:
    build: ./webapp
    image: webapp
    container_name: webapp
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:3.2.11
    container_name: redis

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    ports:
      - 54320:5432
    # volumes:
    #   - ${PWD}/../postgre_data:/var/lib/postgresql/data
